#!/usr/bin/env bash

if ! [ -f Doxyfile ]; then
    echo "You won't need doxygen aliases unless the directory"
    echo "has been prepared for doxygen:"
    echo "  $ doxygen -g"
    exit 1
fi

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    echo "This script must be run with 'source' or '.':"
    echo "  $ . doxy_aliases"
    exit 1
else
    if [ -f Doxyfile_add ]; then
        alias doxygen="(cat Doxyfile; cat Doxyfile_add ) | doxygen -"
        printf $'Creating alias \e[32;1mdoxygen\e[39;22m to incorporate settings in \e[32;1mDoxyfile_add\e[39;22m.\n'
    fi
    alias doxy="xdg-open html/index.html"
    printf $'Creating alias \e[32;1mdoxy\e[39;22m to show documentation in default browser.\n'
fi

