.so fork.tmac
.SH SYNOPSIS
.PP
.B \(shinclude <jsondom.h>
.PP
.   B typedef enum jd_Type_e
.   IR jd_Type ;
.br
.   B typedef struct JNode_s
.   IR JNode ;
.br
.   B typedef struct jd_ParseError_s
.   IR id_ParseError ;
.PP
.pt_jd_parse_file
.pt_jd_destroy
.pt_jd_serialize
.PP
.pt_JDataType
.PP
.pt_JNode
.PP
.pt_jd_ParseError
.PP
